/* Internal implementation support shared by extracted editor widgets. */
#pragma once

#include "tools-sidebar.h"
#include "canvas-preview.h"
#include "layer-stack-widget.h"
#include "timeline-widget.h"
#include "timeline-scroll-zoom-bar.h"
#include "title-properties-panel.h"
#include "effects-panel.h"
#include "effects-presets-panel.h"
#include "effect-preset-catalog.h"
#include "effects/effect-animation-utils.h"
#include "extensions/effect-extension-catalog.h"
#include "properties-panel.h"
#include "fxm-modern-controls.h"

#include "title-data.h"
#include "external-data.h"
#include "title-assets.h"
#include "timecode-spinbox.h"
#include "title-localization.h"
#include "title-preferences.h"
#include "cache-manager.h"
#include "prerender-dock.h"
#include "style-presets.h"
#include "style-preset-runtime.h"
#include "asset-library.h"
#include "image-layer-utils.h"
#include "path-geometry.h"
#include "title-text-layout.h"
#include "ticker-runtime.h"
#include "asset-runtime.h"
#include "frame-rate-provider.h"
#include "title-preview-renderer.h"

#include <QApplication>

#include <QBuffer>
#include <QIODevice>
#include <QPainter>
#include <QBrush>
#include <QPainterPath>
#include <QPolygonF>
#include <QLineF>
#include <QCursor>
#include <QImage>
#include <QImageReader>
#include <QSize>
#include <QSvgRenderer>
#include <QMouseEvent>
#include <QWheelEvent>
#include <QResizeEvent>
#include <QCloseEvent>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QSplitter>
#include <QToolBar>
#include <QAction>
#include <QActionGroup>
#include <QButtonGroup>
#include <QAbstractButton>
#include <QIcon>
#include <QPixmap>
#include <QStringList>
#include <QVariant>
#include <QSet>
#include <QLocale>
#include <QStyle>
#include <QLabel>
#include <QLineEdit>
#include <QPushButton>
#include <QSpinBox>
#include <QDoubleSpinBox>
#include <QSlider>
#include <QComboBox>
#include <QCheckBox>
#include <QGroupBox>
#include <QFormLayout>
#include <QGridLayout>
#include <QFileDialog>
#include <QInputDialog>
#include <QDir>
#include <QDirIterator>
#include <QFileInfo>
#include <QRegularExpression>
#include <QFontDatabase>
#include <QFontMetrics>
#include <QScrollArea>
#include <QScrollBar>
#include <QListWidget>
#include <QStackedWidget>
#include <QSizePolicy>
#include <QFrame>
#include <QSignalBlocker>
#include <QKeyEvent>
#include <QEvent>
#include <QKeySequence>
#include <QAbstractSpinBox>
#include <QAbstractItemModel>
#include <QAbstractItemView>
#include <QTextEdit>
#include <QTextDocument>
#include <QTextCursor>
#include <QTextCharFormat>
#include <QTextBlock>
#include <QTextFragment>
#include <QTextLayout>
#include <QTextOption>
#include <QAbstractTextDocumentLayout>
#include <QDateTime>
#include <QTransform>
#include <QLinearGradient>
#include <QRadialGradient>
#include <QConicalGradient>
#include <QToolButton>
#include <QMenu>
#include <QMenuBar>
#include <QTabWidget>
#include <QTabBar>
#include <QMessageBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDockWidget>
#include <QMainWindow>
#include <QScreen>
#include <QSettings>
#include <QWindow>
#include <QContextMenuEvent>
#include <QTimer>
#include <cmath>
#include <chrono>
#include <algorithm>
#include <vector>
#include <initializer_list>
#include <set>
#include <map>
#include <limits>
#include <utility>
#include <tuple>
#include <functional>

#include <QtColorWidgets/ColorDialog>


/* Ordered implementation modules. Keep this list in source order. */
#include "title-editor-internal/widget-property-helpers.inc"
#include "title-editor-internal/rich-text-color-utils.inc"
#include "title-editor-internal/rich-text-model-adapters.inc"
#include "title-editor-internal/text-layout-rendering.inc"
#include "title-editor-internal/canvas-rendering-helpers.inc"
#include "title-editor-internal/hierarchy-model.inc"
