#include "system-memory.h"
#include "external-data.h"
#include "editor-theme.h"
#include "fxm-modern-controls.h"
#include "title-editor.h"
#include "title-editor-internal.h"
#include "title-logger.h"
#include "title-video-runtime.h"
#include "editor-host-interfaces.h"
#include "flux-encoder-client.h"
#include "recent-projects.h"
#include "project-panel.h"
#include "project-loading-dialog.h"
#include "host-context-provider.h"
#include "layer-transform-3d.h"
#include "title-snapshot.h"
#include "build-info.h"
#include "style-presets.h"
#include "transition-editor-dialog.h"
#include "transition-preset-catalog.h"
#include "text-animator-presets.h"
#include "effect-preset-catalog.h"
#include "effect-runtime.h"

#include <QPointer>
#include <QClipboard>
#include <QScopedValueRollback>
#include <QDesktopServices>
#include <QFile>
#include <QFileInfo>
#include <QMessageBox>
#include <QMouseEvent>
#include <QShowEvent>
#include <QMimeData>
#include <QSettings>
#include <QStandardPaths>
#include <QUrl>
#include <QScreen>
#include <QGuiApplication>
#include <QWindow>
#include <QTimer>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QList>
#include <QDir>
#include <QLineEdit>
#include <QPlainTextEdit>
#include <QComboBox>
#include <QSet>
#include <QMap>
#include <QDirIterator>
#include <QDateTime>
#include <QCheckBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QInputDialog>
#include <QLabel>
#include <QVBoxLayout>
#include <QStatusBar>
#include <QPalette>
#include <QStringList>
#include <QToolButton>
#include <QPainter>
#include <QPaintEvent>
#include <QXmlStreamReader>
#include <QDataStream>
#include <QSaveFile>
#include <QRadioButton>
#include <QScrollArea>
#include <QVector>
#include <QCryptographicHash>
#include <QImageReader>
#include <QFontMetricsF>
#include <QFontDatabase>
#include <QApplication>
#include <QEvent>
#include <QFontMetrics>
#include <QMutex>
#include <QMutexLocker>
#include <QVariant>

#include <array>
#include <cmath>
#include <algorithm>
#include <chrono>
#include <cstring>
#include <functional>
#include <initializer_list>
#include <limits>


#include "long-press-tool-button.h"

#include "open-color-palette.h"

/* Ordered implementation modules. Keep this list in source order. */
#include "title-editor/window-session.inc"
#include "title-editor/ui-construction.inc"
#include "title-editor/panels-colors.inc"
#include "title-editor/commands-docks.inc"
#include "title-editor/document-shape-editing.inc"
#include "title-editor/playback-cache-preferences.inc"
#include "title-editor/layout-template-tools.inc"
#include "title-editor/editor-audio-preview.inc"
#include "title-editor/signal-handlers.inc"
#include "title-editor/editor-events.inc"
#include "title-editor/import-documents.inc"
