/*
 * title-dock.cpp
 */

#include "title-dock.h"
#include "fxm-modern-controls.h"
#include "title-data.h"
#include "host-context-provider.h"
#include "title-preview-renderer.h"
#include "title-serialization-schema.h"
#include "live-text-cue-utils.h"
#include "title-snapshot.h"
#include "canvas-preview.h"
#include "title-assets.h"
#include "timecode-spinbox.h"
#include "title-localization.h"
#include "cache-manager.h"
#include "title-logger.h"
#include "image-layer-utils.h"
#include "effect-runtime.h"
#include "extensions/effect-extension-catalog.h"
#include "build-info.h"
#include "external-data-settings-dialog.h"
#include "external-data-binding-dialog.h"
#include "external-data-table-mapping-dialog.h"
#include "external-data.h"
#include "external-data-provider.h"
#include "external-data-log.h"

#include <QAction>
#include <QBuffer>
#include <QCheckBox>
#include <QBrush>
#include <QColor>
#include <QComboBox>
#include <QDateTime>
#include <QDir>
#include <QDirIterator>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDrag>
#include <QDragEnterEvent>
#include <QDragLeaveEvent>
#include <QDragMoveEvent>
#include <QDropEvent>
#include <QInputDialog>
#include <QLabel>
#include <QIODevice>
#include <QItemSelectionModel>
#include <QMenu>
#include <QMimeData>
#include <QTextEdit>
#include <QMessageBox>
#include <QMetaObject>
#include <QMainWindow>
#include <QVBoxLayout>
#include <QFormLayout>
#include <QHBoxLayout>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QIcon>
#include <QStyle>
#include <QStyleOptionButton>
#include <QStyledItemDelegate>
#include <QApplication>
#include <QToolButton>
#include <QToolBar>
#include <QDoubleSpinBox>
#include <QSettings>
#include <QWidgetAction>
#include <QPushButton>
#include <QListView>
#include <QListWidget>
#include <QTreeWidget>
#include <QUrl>
#include <QFont>
#include <QFontDatabase>
#include <QFrame>
#include <QFocusEvent>
#include <QSizePolicy>
#include <QSize>
#include <QString>
#include <QStringList>
#include <QHeaderView>
#include <QHelpEvent>
#include <QKeyEvent>
#include <QLineEdit>
#include <QPlainTextEdit>
#include <QPointer>
#include <QSpinBox>
#include <QTextOption>
#include <QTextDocument>
#include <QMouseEvent>
#include <QResizeEvent>
#include <QPainter>
#include <QPen>
#include <QSet>
#include <QPixmap>
#include <QPolygonF>
#include <QSignalBlocker>
#include <QSplitter>
#include <QTabWidget>
#include <QTableWidgetItem>
#include <QTimer>
#include <QToolTip>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QColorDialog>
#include <QEvent>
#include <QRegularExpression>
#include <memory>
#include <algorithm>
#include <functional>
#include <numeric>
#include <iterator>
#include <sstream>
#include <array>
#include <cmath>
#include <cstring>


#include "long-press-tool-button.h"

/* Used by dock-lifecycle.inc before the implementation module that defines it. */
static bool title_has_bound_host_source(const std::string &title_id);

/* Ordered implementation modules. Keep this list in source order. */
#include "title-dock/template-library-helpers.inc"
#include "title-dock/import-export-helpers.inc"
#include "title-dock/dock-ui.inc"
#include "title-dock/collapsible-titles.inc"
#include "title-dock/dock-lifecycle.inc"
#include "title-dock/list-selection-cues.inc"
#include "title-dock/live-text-cache-playlist.inc"
#include "title-dock/title-actions.inc"
