from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def test_version_and_cache_revision_are_276():
    assert 'set(OBS_FXM_DEVELOPMENT_VERSION "276")' in read("CMakeLists.txt")
    assert '#define FXM_DEVELOPMENT_VERSION "276"' in read("src/core/build-info.h")
    assert '|gpu-text-pipeline=276' in read(
        "../../packages/flux-common/Shared/rendering-engine/title-source/source-lifecycle-playback.inc"
    )


def test_gpu_shaping_never_uses_qfont_stretch_for_character_scale():
    source = read("src/text/title-text-layout-qt.cpp")
    font_block = source[source.index("static QFont font_from_rich_format"):
                        source.index("static QTextCharFormat qtext_format")]
    assert "font.setStretch(100);" in font_block
    assert "horizontal_stretch_percent" not in font_block
    assert "apply_line_horizontal_character_scale" in source
    assert "glyph.x = new_x + (old_glyph_x - old_x) * factor;" in source
    assert "cluster.width = new_width;" in source
    assert "cursor.x = new_x + (cursor.x - old_x) * factor;" in source


def test_rich_text_scale_is_resolved_per_canonical_cluster():
    source = read("src/text/title-text-layout-qt.cpp")
    assert "kLayoutScaleXProperty" in source
    assert "kLayoutScaleYProperty" in source
    assert "layout.glyphRuns(" in source
    assert "glyph_run.stringIndexes()" in source
    assert "rich_text_format_at(request.document, cluster_byte)" in source
    assert "mapped.formats" in source
    assert "glyph.scale_x = std::clamp(" in source
    assert "glyph.scale_y = std::clamp(" in source
    assert "line_qstart + raw" not in source


def test_atlas_is_unscaled_and_gpu_quad_applies_each_axis_once():
    source = read("src/rendering/title-gpu-text-renderer.cpp")
    assert "H/V Scale is vertex geometry, not atlas identity" in source
    assert "glyph_scale_x" in source and "glyph_scale_y" in source
    assert "atlas_glyph.width) * glyph_scale_x" in source
    assert "atlas_glyph.height) * glyph_scale_y" in source
    assert "(atlas_glyph.offset_x - padding) * glyph_scale_x" in source
    assert "(atlas_glyph.offset_y - padding) * glyph_scale_y" in source


def test_canonical_model_composes_multiple_sparse_properties():
    header = read("src/text/title-rich-text.h")
    model = read("src/text/title-rich-text.cpp")
    adapters = read("src/editor/title-editor-internal/rich-text-model-adapters.inc")
    assert "RichTextCharScaleX" in header and "RichTextCharScaleY" in header
    assert "RichTextCharFillColor" in header and "RichTextCharStroke" in header
    assert "rich_text_document_apply_default_char_format" in header
    assert "range.mask &= ~mask;" in model
    assert "rich_text_merge_char_format(effective, range.format, range.mask);" in model
    assert "rich_text_document_apply_format(doc, start, end - start, format, mask);" in adapters


def test_qtext_adapter_has_provenance_and_cannot_persist_auto_formatting():
    colors = read("src/editor/title-editor-internal/rich-text-color-utils.inc")
    adapters = read("src/editor/title-editor-internal/rich-text-model-adapters.inc")
    assert "RichTextPropCanonicalAdapter" in colors
    assert "out.setProperty(RichTextPropCanonicalAdapter, true);" in colors
    assert "RichTextPropAutoGenerated" in adapters
    assert "RichTextPropCanonicalAdapter" in adapters
    assert "manual_mask = 0" in adapters or "mask = 0" in adapters
    assert "qplain.toUtf8().toStdString()" in adapters


def test_properties_and_keyboard_formatting_share_title_history():
    header = read("src/editor/title-editor.h")
    tools = read("src/editor/title-editor/layout-template-tools.inc")
    canvas_header = read("src/canvas/canvas-preview.h")
    canvas = read("src/canvas/canvas-preview-inline-text.cpp")
    wiring = read("src/editor/title-editor/document-shape-editing.inc")
    assert "begin_text_property_transaction" in header
    assert "commit_text_property_transaction" in header
    assert "void TitleEditor::begin_text_property_transaction" in tools
    assert "void TitleEditor::commit_text_property_transaction" in tools
    assert "text_property_change_started" in canvas_header
    assert "text_property_change_committed" in canvas_header
    assert "emit text_property_change_started(layer_id);" in canvas
    assert "emit text_property_change_committed(layer->id);" in canvas
    assert "&CanvasPreview::text_property_change_started" in wiring
    assert "&CanvasPreview::text_property_change_committed" in wiring


def test_text_boundaries_use_explicit_utf8():
    paths = [
        "src/canvas/canvas-preview-inline-text.cpp",
        "src/editor/title-editor-internal/rich-text-model-adapters.inc",
        "src/editor/title-editor-internal/canvas-rendering-helpers.inc",
        "../../packages/flux-common/Shared/rendering-engine/title-source/gpu-masks-groups-cache.inc",
        "../../packages/flux-common/Shared/rendering-engine/title-source/layer-evaluation-layout.inc",
        "../../packages/flux-common/Shared/rendering-engine/title-source/source-runtime.inc",
        "src/editor/style-presets.cpp",
    ]
    joined = "\n".join(read(path) for path in paths)
    assert joined.count("toUtf8().toStdString()") >= 8


def test_audit_document_records_authority_and_validation_boundary():
    audit = read("docs/TEXT_SYSTEM_AUDIT_276.md")
    assert "Authority matrix" in audit
    assert "RichTextDocument" in audit
    assert "QTextDocument" in audit
    assert "GPU glyph atlas" in audit
    assert "Undo/Redo" in audit
    assert "Validation boundary" in audit


def test_horizontal_fit_scales_the_glyph_quad_and_not_only_spacing():
    layout = read("src/text/title-text-layout-qt.cpp")
    assert "glyph.scale_x = std::clamp(glyph.scale_x * factor" in layout
    assert "fit mode compresses advances only" in layout


def test_inline_keyboard_formatting_is_one_title_history_transaction():
    inline = read("src/canvas/canvas-preview-inline-text.cpp")
    start = inline.index("emit text_property_change_started(layer_id);")
    end = inline.index("emit text_property_change_committed(layer->id);", start)
    formatting = inline[start:end]
    assert "emit text_edit_changed(layer" not in formatting
