#!/usr/bin/env python3
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]

def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8", errors="replace")

cmake = read("CMakeLists.txt")
build = read("src/core/build-info.h")
manifest = json.loads(read("tests/test-suite-manifest.json"))
shader = read("../../packages/flux-common/Shared/rendering-engine/title-source/gpu-effects-transitions.inc")
shadow = read("../../packages/flux-common/Shared/rendering-engine/title-source/gpu-session-lifecycle.inc")
data = read("src/core/title-data.cpp")
properties = read("src/editor/properties-panel/popup-state.inc")
title_properties = read("src/editor/title-properties-panel.cpp")
runtime = read("../../packages/flux-common/Shared/rendering-engine/title-source/gpu-presentation-readback.inc")
canvas = read("src/canvas/canvas-preview/editor-3d-tools.inc")
visual_hash = read("src/cache/cache-manager/visual-hash-keying.inc")
readme = read("README.md")
changelog = read("docs/CHANGELOG.md")

assert int(re.search(r'OBS_FXM_DEVELOPMENT_VERSION "(\d+)"', cmake).group(1)) >= 397
assert int(re.search(r'FXM_DEVELOPMENT_VERSION "(\d+)"', build).group(1)) >= 397
assert manifest["development_version"] >= 397
assert "## Development Version 397 — continuous text shadows and Source Size floor" in changelog
assert "Development Version 397 text-shadow continuity" in readme

# Text-like cutout casters use projected-footprint conservative alpha only in
# the shadow writer. Solid/image/video casters keep the original single sample.
for token in (
    "uniform int conservativeAlpha;",
    "uniform float2 sourceTexelSize;",
    "if (conservativeAlpha != 0)",
    "float2(fwidth(v.uv.x), fwidth(v.uv.y))",
    "projected footprint",
):
    assert token in shader
assert shader.count("image.Sample(textureSampler") >= 5
for token in (
    "bool conservative_alpha = false;",
    "const bool text_like_caster =",
    "layer->type == LayerType::Text",
    "layer->type == LayerType::Clock",
    "layer->type == LayerType::Ticker",
    'fxm_effect_param(\n        session->shadow_effect, "conservativeAlpha")',
    'fxm_effect_param(\n        session->shadow_effect, "sourceTexelSize")',
    "caster.conservative_alpha ? 1 : 0",
    "1.0f / static_cast<float>(std::max(1u, caster.entry->width))",
):
    assert token in shadow

# Source Size cannot be authored, loaded or evaluated below 0.1 px.
assert 'read_prop("source_size", light.source_size, 0.1, 100000.0);' in data
assert "mk_dspin(0.1, 100000.0, 0.1)" in properties
assert "make_light_spin(0.1, 100000.0, 0.1, 2)" in title_properties
assert "light.source_size.evaluate(title_time), 0.1, 100000.0" in runtime
assert "0.1, light.source_size.evaluate(playhead_)" in canvas

# Cache identities must not reuse frames generated by the old shadow writer.
assert "v68-conservative-text-shadow-alpha-min-source-size" in visual_hash
assert "v43-conservative-text-shadow-alpha-min-source-size" in runtime

current = "tests/development_version_397_text_shadow_source_size_contract_test.py"

def contains(value):
    if isinstance(value, list):
        return current in value or any(contains(item) for item in value)
    if isinstance(value, dict):
        return any(contains(item) for item in value.values())
    return False

assert contains(manifest)
print("Development Version 397 text shadow and Source Size contract: PASS")
